//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace footbalform1.mode1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meydanca00
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meydanca00()
        {
            this.Umumi00 = new HashSet<Umumi00>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Otaqlar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Umumi00> Umumi00 { get; set; }
    }
}
